# Generated by Django 5.0.3 on 2026-03-08 11:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('basic', 'Basic Details'), ('personal', 'Personal'), ('experience', 'Experience'), ('education', 'Education Details'), ('official', 'Official Purpose')], default='personal', max_length=20)),
            ],
            options={
                'ordering': ['section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(help_text='e.g. EMP-0001', max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('address', models.TextField(blank=True)),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('reference_phone', models.CharField(blank=True, max_length=20)),
                ('experience_details', models.TextField(blank=True, help_text='Past experience summary')),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('qualification_document', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('description', models.TextField(blank=True, help_text='Role or additional remarks')),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('resigned', models.BooleanField(default=False)),
                ('resign_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='hr.employeecustomfield')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='hr.employeeprofile')),
            ],
            options={
                'unique_together': {('employee', 'field')},
            },
        ),
    ]
