# Generated by Django 5.0.3 on 2026-03-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_trackingformtoken'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingformlink',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_form_links', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='trackingshipment',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_shipments', to='tenants.tenant'),
        ),
    ]
