# Generated by Django 5.0.3 on 2026-03-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
    ]
