# Generated by Django 5.0.3 on 2026-04-06 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingFormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(default=list)),
                ('default_field_overrides', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Manufacturing Form Schema',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingStatusFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_key', models.CharField(help_text='The manufacturing status key that triggers this flow.', max_length=50, unique=True)),
                ('action', models.CharField(choices=[('notify_only', 'Notify Only'), ('mark_complete', 'Mark as Complete')], default='notify_only', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['status_key'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mfg_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(default='not_started', max_length=50)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('order', 'From Order'), ('lead', 'From Lead')], default='manual', max_length=20)),
                ('order_ref', models.CharField(blank=True, help_text='Order number if sourced from Orders module.', max_length=100)),
                ('lead_ref', models.CharField(blank=True, help_text='Lead name/ref if sourced from CRM.', max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
