# Generated by Django 5.0.3 on 2026-03-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('meta', 'Meta / Facebook'), ('shopify', 'Shopify'), ('online', 'Online Order'), ('manual', 'Manual Entry'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('form', 'Form Submission'), ('excel', 'Excel Import')], default='manual', max_length=20),
        ),
    ]
