# Generated by Django 5.0.3 on 2026-03-07 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_crm', models.BooleanField(default=True)),
                ('module_products', models.BooleanField(default=True)),
                ('module_stock', models.BooleanField(default=True)),
                ('module_orders', models.BooleanField(default=True)),
                ('module_warehouse', models.BooleanField(default=True)),
                ('module_invoices', models.BooleanField(default=True)),
                ('module_dispatch', models.BooleanField(default=True)),
                ('module_tracking', models.BooleanField(default=False)),
                ('module_manufacturing', models.BooleanField(default=False)),
                ('module_hr', models.BooleanField(default=False)),
                ('module_analytics', models.BooleanField(default=True)),
                ('theme_color', models.CharField(default='#2563eb', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('company_name_override', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('order_requires_approval', models.BooleanField(default=True, help_text='If True, online orders require admin approval before warehouse processing.')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Configuration',
            },
        ),
    ]
