# Generated by Django 5.0.3 on 2026-03-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_company_rules_custom_fields'),
        ('tenants', '0007_trackingformtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfig',
            name='tenant',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='config', to='tenants.tenant'),
        ),
    ]
