# Generated by Django 5.0.3 on 2026-03-15 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_fix_tenant_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('crm', 'CRM'), ('products', 'Products'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('invoices', 'Invoices'), ('dispatch', 'Dispatch'), ('settings', 'Settings'), ('hr', 'HR'), ('warehouses', 'Warehouses'), ('tracking', 'Tracking')], db_index=True, max_length=50)),
                ('action', models.CharField(default='history_deleted', max_length=30)),
                ('summary_text', models.CharField(max_length=500)),
                ('records_deleted', models.PositiveIntegerField(default=1)),
                ('performed_by_email', models.CharField(blank=True, max_length=254)),
                ('performed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Summary',
                'verbose_name_plural': 'Audit Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('crm', 'CRM'), ('products', 'Products'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('invoices', 'Invoices'), ('dispatch', 'Dispatch'), ('settings', 'Settings'), ('hr', 'HR'), ('warehouses', 'Warehouses'), ('tracking', 'Tracking')], db_index=True, max_length=50)),
                ('action', models.CharField(max_length=30)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('performed_by_email', models.CharField(blank=True, max_length=254)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module History',
                'verbose_name_plural': 'Module Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
