# Generated by Django 5.0.3 on 2026-03-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_module_history_auditsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='buffer_stock_auto_enabled',
            field=models.BooleanField(default=False, help_text='When True, monthly analysis suggests buffer from movement history.'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='buffer_stock_default',
            field=models.PositiveIntegerField(blank=True, help_text='Default buffer stock when product has none. Manual per-product overrides this.', null=True),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='fast_moving_alert_enabled',
            field=models.BooleanField(default=True, help_text='Send email + show in-app alert when product is fast-moving in a month.'),
        ),
    ]
