# Generated by Django 5.0.3 on 2026-04-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_tenantconfig_crm_bulk_assign_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='use_default_theme',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='theme_color',
            field=models.CharField(default='#0f172a', max_length=20),
        ),
    ]
