# Generated by Django 5.0.3 on 2026-03-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_fix_do_nothing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(choices=[('round_robin', 'Round Robin — equal rotation'), ('pool', 'Pool — fixed batch, refill on finish'), ('custom', 'Custom — admin-defined count per employee'), ('off', 'Off — no auto-assignment')], default='off', max_length=20)),
                ('pool_batch_size', models.IntegerField(default=4)),
                ('finished_statuses', models.JSONField(default=list, help_text='List of status keys that count as finished (e.g. ["order_created","lost"])')),
                ('employees', models.JSONField(default=list)),
                ('rr_pointer', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lead Assignment Config',
            },
        ),
    ]
