# Generated by Django 5.0.3 on 2026-04-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_leadform_defaults_source_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadassignmentconfig',
            name='assignments_by_source',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"meta": [1,2], "whatsapp": [3]} — user pk list per Lead.source'),
        ),
        migrations.AlterField(
            model_name='leadassignmentconfig',
            name='source_rr_pointers',
            field=models.JSONField(blank=True, default=dict, help_text='Internal next index per source for round-robin.'),
        ),
        migrations.AlterField(
            model_name='leadformschema',
            name='default_field_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides for built-in fields: order, required, label, pattern (regex for phone).'),
        ),
    ]
