# Generated by Django 5.0.3 on 2026-03-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_model',
            field=models.CharField(choices=[('b2b', 'B2B (Business to Business)'), ('b2c', 'B2C (Business to Consumer)'), ('both', 'B2B & B2C')], default='b2b', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
