# Generated by Django 5.0.3 on 2026-03-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_business_model_tenant_logo_tenant_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_crm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_dispatch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_invoices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_manufacturing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_products',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='module_warehouse',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='business_model',
            field=models.CharField(choices=[('b2b', 'B2B — Business to Business'), ('b2c', 'B2C — Business to Consumer'), ('d2c', 'D2C — Direct to Consumer'), ('hybrid', 'Hybrid — Mixed Model'), ('marketplace', 'Marketplace'), ('saas', 'SaaS / Software'), ('services', 'Services / Consulting'), ('other', 'Other')], default='b2b', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Tagline or short description shown in UI', max_length=300),
        ),
    ]
