# Generated by Django 5.0.3 on 2026-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_contact_email_tenant_module_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='mobile_app_bundle_id',
            field=models.CharField(blank=True, help_text='e.g. com.trading.acmecorp — used for app store publishing', max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mobile_app_enabled',
            field=models.BooleanField(default=False, help_text='Enable a white-label mobile app for this client (Flutter SaaS model)'),
        ),
    ]
