# Generated by Django 5.0.3 on 2026-03-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_mobile_app_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='mobile_app_bundle_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='mobile_app_enabled',
        ),
    ]
