# Generated by Django 5.0.3 on 2026-04-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_crm_phone_regex_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='theme_color',
            field=models.CharField(default='#0f172a', help_text='Sidebar branding color', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='use_default_theme',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='crm_phone_regex_presets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
