import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
        ('orders', '0004_custom_order_status_flow'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── InvoiceSettings ──
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('no_gst', 'No GST / Non-Taxable'), ('indian_gst', 'Indian GST Compliant')], default='no_gst', max_length=20)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('supplier_address', models.TextField(blank=True)),
                ('supplier_city', models.CharField(blank=True, max_length=100)),
                ('supplier_state', models.CharField(blank=True, max_length=5)),
                ('supplier_pincode', models.CharField(blank=True, max_length=10)),
                ('supplier_gstin', models.CharField(blank=True, max_length=15)),
                ('supplier_pan', models.CharField(blank=True, max_length=10)),
                ('supplier_cin', models.CharField(blank=True, max_length=21)),
                ('supplier_phone', models.CharField(blank=True, max_length=20)),
                ('supplier_email', models.EmailField(blank=True, max_length=254)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_upi_id', models.CharField(blank=True, max_length=100)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('next_invoice_number', models.IntegerField(default=1)),
                ('proforma_prefix', models.CharField(default='PI', max_length=10)),
                ('next_proforma_number', models.IntegerField(default=1)),
                ('default_due_days', models.IntegerField(default=30)),
                ('default_terms', models.TextField(blank=True, default='Goods once sold will not be taken back or exchanged.')),
                ('e_invoicing_enabled', models.BooleanField(default=False)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='tenants.tenant')),
            ],
            options={'verbose_name': 'Invoice Settings', 'verbose_name_plural': 'Invoice Settings'},
        ),

        # ── CustomInvoiceStatus ──
        migrations.CreateModel(
            name='CustomInvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['order', 'id']},
        ),

        # ── InvoiceFlowAction ──
        migrations.CreateModel(
            name='InvoiceFlowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_key', models.CharField(max_length=50, unique=True)),
                ('target_module', models.CharField(choices=[('none', 'Stay in Invoices only'), ('orders', 'Orders'), ('warehouse', 'Warehouse / Inventory'), ('dispatch', 'Dispatch'), ('crm', 'CRM')], default='none', max_length=30)),
                ('action', models.CharField(choices=[('mark_dispatch', 'Mark for Dispatch'), ('send_to_warehouse', 'Send to Warehouse'), ('notify_only', 'Notify Only')], default='notify_only', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={'ordering': ['status_key']},
        ),

        # ── InvoiceLineItem ──
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300)),
                ('hsn_sac', models.CharField(blank=True, max_length=8)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
            options={'ordering': ['id']},
        ),

        # ── Alter Invoice fields ──

        # Change order from OneToOneField to nullable ForeignKey
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),

        # Add new Invoice fields
        migrations.AddField(model_name='invoice', name='invoice_type',
            field=models.CharField(choices=[('tax_invoice', 'Tax Invoice'), ('bill_of_supply', 'Bill of Supply'), ('proforma', 'Proforma Invoice'), ('cash_memo', 'Cash Memo')], default='bill_of_supply', max_length=20)),
        migrations.AddField(model_name='invoice', name='supply_type',
            field=models.CharField(choices=[('b2b', 'B2B (Business to Business)'), ('b2c', 'B2C (Business to Consumer)')], default='b2b', max_length=5)),
        migrations.AddField(model_name='invoice', name='supplier_name',
            field=models.CharField(blank=True, max_length=200)),
        migrations.AddField(model_name='invoice', name='supplier_address',
            field=models.TextField(blank=True)),
        migrations.AddField(model_name='invoice', name='supplier_gstin',
            field=models.CharField(blank=True, max_length=15)),
        migrations.AddField(model_name='invoice', name='supplier_state',
            field=models.CharField(blank=True, max_length=5)),
        migrations.AddField(model_name='invoice', name='supplier_state_code',
            field=models.CharField(blank=True, max_length=5)),
        migrations.AddField(model_name='invoice', name='recipient_name',
            field=models.CharField(default='', max_length=200)),
        migrations.AddField(model_name='invoice', name='recipient_address',
            field=models.TextField(blank=True)),
        migrations.AddField(model_name='invoice', name='recipient_city',
            field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='invoice', name='recipient_state',
            field=models.CharField(blank=True, max_length=5)),
        migrations.AddField(model_name='invoice', name='recipient_state_code',
            field=models.CharField(blank=True, max_length=5)),
        migrations.AddField(model_name='invoice', name='recipient_pincode',
            field=models.CharField(blank=True, max_length=10)),
        migrations.AddField(model_name='invoice', name='recipient_gstin',
            field=models.CharField(blank=True, max_length=15)),
        migrations.AddField(model_name='invoice', name='recipient_phone',
            field=models.CharField(blank=True, max_length=20)),
        migrations.AddField(model_name='invoice', name='recipient_email',
            field=models.EmailField(blank=True, max_length=254)),
        migrations.AddField(model_name='invoice', name='place_of_supply',
            field=models.CharField(blank=True, max_length=5)),
        migrations.AddField(model_name='invoice', name='is_gst',
            field=models.BooleanField(default=False)),
        migrations.AddField(model_name='invoice', name='is_reverse_charge',
            field=models.BooleanField(default=False)),
        migrations.AddField(model_name='invoice', name='is_intra_state',
            field=models.BooleanField(default=True)),
        migrations.AddField(model_name='invoice', name='total_taxable_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='invoice', name='total_cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='invoice', name='total_sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='invoice', name='total_igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='invoice', name='total_cess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='invoice', name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='invoice', name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6)),
        migrations.AddField(model_name='invoice', name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='invoice', name='grand_total_words',
            field=models.CharField(blank=True, max_length=500)),
        migrations.AddField(model_name='invoice', name='bank_name',
            field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='invoice', name='bank_account_number',
            field=models.CharField(blank=True, max_length=30)),
        migrations.AddField(model_name='invoice', name='bank_ifsc',
            field=models.CharField(blank=True, max_length=11)),
        migrations.AddField(model_name='invoice', name='bank_branch',
            field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='invoice', name='terms',
            field=models.TextField(blank=True)),
        migrations.AddField(model_name='invoice', name='irn',
            field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name='invoice', name='qr_code_data',
            field=models.TextField(blank=True)),
    ]
