# Generated by Django 5.0.3 on 2026-03-12 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_courier_partner_contact_phone_pincode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominvoicestatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dispatchflowaction',
            name='default_tracking_status',
            field=models.CharField(blank=True, help_text='When flow is update_tracking or transfer_to_tracking, default status in tracking.', max_length=30),
        ),
        migrations.AlterField(
            model_name='dispatchsettings',
            name='flow_after_dispatch',
            field=models.CharField(choices=[('notify_only', 'Notify only'), ('mark_delivered', 'Mark as delivered when confirmed'), ('update_tracking', 'Update tracking status'), ('transfer_to_tracking', 'Transfer to tracking module'), ('none', 'No automatic next step')], default='notify_only', help_text='Next step after an order/invoice is dispatched.', max_length=30),
        ),
        migrations.AlterField(
            model_name='dispatchsticker',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='irn',
            field=models.CharField(blank=True, help_text='Invoice Reference Number for e-invoicing', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text='State code — determines CGST+SGST vs IGST', max_length=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='recipient_state',
            field=models.CharField(blank=True, help_text='State code', max_length=5),
        ),
        migrations.AlterField(
            model_name='invoiceflowaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='hsn_sac',
            field=models.CharField(blank=True, help_text='HSN/SAC code (6-8 digits, mandatory for GST)', max_length=8),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST rate percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit',
            field=models.CharField(default='NOS', help_text='UQC — NOS, KGS, MTR, LTR, PCS, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='default_currency',
            field=models.CharField(default='INR', help_text='ISO 4217 currency code', max_length=5),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='msme_number',
            field=models.CharField(blank=True, help_text='UDYAM registration number', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='msme_type',
            field=models.CharField(blank=True, help_text='e.g. Micro, Small, Medium', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='supplier_gstin',
            field=models.CharField(blank=True, help_text='15-character GSTIN', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='supplier_state',
            field=models.CharField(blank=True, help_text='State code from INDIAN_STATES', max_length=5),
        ),
    ]
