# Generated by Django 5.0.3 on 2026-03-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_fix_do_nothing'),
        ('tenants', '0007_trackingformtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierpartner',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courier_partners', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='customdispatchstatus',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispatch_statuses', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='dispatchflowaction',
            name='tenant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispatch_flow_actions', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='dispatchsettings',
            name='tenant',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispatch_settings', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='tenant',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_settings', to='tenants.tenant'),
        ),
    ]
