# Generated by Django 5.0.3 on 2026-03-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_fix_tenant_fk'),
        ('warehouses', '0009_custominventorystatus_inventoryflowaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inventory_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='warehouses.inventoryapproval'),
        ),
    ]
