# Generated by Django 5.0.3 on 2026-03-12 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_fix_remaining_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('source_module', models.CharField(choices=[('orders', 'Orders'), ('crm', 'CRM / Leads'), ('invoices', 'Invoices'), ('dispatch', 'Dispatch'), ('manual', 'Manual Entry'), ('other', 'Other')], default='manual', max_length=30)),
                ('source_reference', models.CharField(blank=True, help_text='Reference ID from source module (order number, lead ID, etc.)', max_length=200)),
                ('requested_action', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('reserve', 'Reserve Stock'), ('transfer', 'Transfer'), ('dispatch', 'Send to Dispatch'), ('other', 'Other')], default='stock_out', max_length=30)),
                ('next_module', models.CharField(blank=True, default='', help_text='Module to forward to after approval (dispatch, invoices, etc.)', max_length=30)),
                ('items', models.JSONField(default=list, help_text='[{"product_id":1,"product_name":"...","quantity":5,"notes":""},...]')),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_approvals', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_incoming', to='warehouses.warehouse')),
                ('requested_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_requests', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
