# Generated by Django 5.0.3 on 2026-03-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_inventoryapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInventoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryFlowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_key', models.CharField(max_length=50, unique=True)),
                ('target_module', models.CharField(choices=[('none', 'Stay in Inventory only'), ('dispatch', 'Dispatch'), ('invoices', 'Invoices'), ('orders', 'Orders'), ('crm', 'CRM')], default='none', max_length=30)),
                ('action', models.CharField(choices=[('forward_dispatch', 'Forward to Dispatch'), ('forward_invoices', 'Forward to Invoices'), ('forward_orders', 'Forward to Orders'), ('execute_stock', 'Execute Stock Movement'), ('notify_only', 'Notify Only')], default='notify_only', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['status_key'],
            },
        ),
        migrations.AlterField(
            model_name='inventoryapproval',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
