# Generated by Django 5.0.3 on 2026-03-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_add_inventoryapproval_lead'),
        ('warehouses', '0009_custominventorystatus_inventoryflowaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryapproval',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_approvals', to='crm.lead'),
        ),
    ]
