# Generated by Django 5.0.3 on 2026-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0010_add_inventoryapproval_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='public_access_token',
            field=models.CharField(blank=True, help_text='Unique token for third-party warehouse view link. Auto-generated when type is Third Party.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('our', 'Our Warehouse'), ('third_party', 'Third Party')], default='our', help_text='Our Warehouse = owned by us. Third Party = external; share link with incharge to view stock & mark usage.', max_length=20),
        ),
    ]
