# Generated by Django 5.0.3 on 2026-03-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_custom_fields_product_custom_data'),
        ('warehouses', '0011_add_warehouse_type_and_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('fast_moving', 'Fast Moving'), ('low_stock', 'Low Stock')], db_index=True, max_length=20)),
                ('year_month', models.CharField(blank=True, max_length=7)),
                ('message', models.CharField(max_length=500)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_month', models.CharField(db_index=True, max_length=7)),
                ('total_in', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_out', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('movement_count', models.PositiveIntegerField(default=0)),
                ('is_fast_moving', models.BooleanField(default=False, help_text='True when out-movements are in top percentile for the month.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_monthly_summaries', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Stock Monthly Summaries',
                'ordering': ['-year_month', 'product'],
                'unique_together': {('product', 'year_month')},
            },
        ),
    ]
