# Generated by Django 5.0.3 on 2026-04-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0012_stock_monthly_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryapproval',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full snapshot of upstream data from source module (lead custom fields, order data, etc.).'),
        ),
    ]
